/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

import Clases.Computadora;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author UPN
 */
public class frmComputadora extends javax.swing.JFrame {

    private final Computadora obj;
    int num = 0;
    
    /**
     * Creates new form frmComputadora
     */
    public frmComputadora() {
        initComponents();
        obj = new Computadora();
        listar();
        this.txtidComputadora.requestFocus();//para que aparesca el cursor en el txt
        this.setLocationRelativeTo(null);//para que la ventana se cite en el medio   
    }
    private int CalculoPrecio(){
        int men, total;
        men = Integer.parseInt(this.txtMemoriaram.getText());
        total = men * 400;
        return total;
    }
            
    private void limpiar(){
        this.txtidComputadora.setText("");
        this.txtProcesador.setText("");
        this.txtMemoriaram.setText("");
        this.cboTDDuro.setSelectedIndex(0);
        this.txtCapDDuro.setText("");
        this.cboMPMadre.setSelectedIndex(0);
        this.txtModeloPMadre.setText("");
        this.txtidComputadora.requestFocus();//para que aparesca el cursor en el txt
    }
    
    private void listar(){
        this.tbDatos.setModel(obj.getDatos());
    }
    
    private void ingresar(){
        int Total = CalculoPrecio();
        obj.setIdcomputadora(Integer.parseInt(this.txtidComputadora.getText()));
        obj.setProcesador(this.txtProcesador.getText());
        obj.setMemoriaram(Integer.parseInt(this.txtMemoriaram.getText()));       
        obj.setTipodiscoduro(this.cboTDDuro.getSelectedItem().toString());
        obj.setCapacidaddiscoduro(Integer.parseInt(this.txtCapDDuro.getText()));
        obj.setMarcaplacamadre(this.cboMPMadre.getSelectedItem().toString());
        obj.setModeloplacamadre(this.txtModeloPMadre.getText());
        obj.setPrecio(Total);
        
        if(num == 0){
            int regs = obj.InsertarDatos(obj.getIdcomputadora(), obj.getProcesador(), 
                    obj.getMemoriaram(), obj.getTipodiscoduro(),obj.getCapacidaddiscoduro(),
                    obj.getMarcaplacamadre(), obj.getModeloplacamadre(), obj.getPrecio());
            if(regs>0){
                listar();
                limpiar();
            }
        }
        
    }
    
    private void actualizar(){
        int Total = CalculoPrecio();
        obj.setIdcomputadora(Integer.parseInt(this.txtidComputadora.getText()));
        obj.setProcesador(this.txtProcesador.getText());
        obj.setMemoriaram(Integer.parseInt(this.txtMemoriaram.getText()));       
        obj.setTipodiscoduro(this.cboTDDuro.getSelectedItem().toString());
        obj.setCapacidaddiscoduro(Integer.parseInt(this.txtCapDDuro.getText()));
        obj.setMarcaplacamadre(this.cboMPMadre.getSelectedItem().toString());
        obj.setModeloplacamadre(this.txtModeloPMadre.getText());
        obj.setPrecio(Total);
           
        int regs = obj.ActualizarDatos(obj.getIdcomputadora(), obj.getProcesador(), 
            obj.getMemoriaram(), obj.getTipodiscoduro(),obj.getCapacidaddiscoduro(),
            obj.getMarcaplacamadre(), obj.getModeloplacamadre(), obj.getPrecio());
        if(regs>0){
            listar();
            limpiar();
            num = 0;
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila");
        }      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCapDDuro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtidComputadora = new javax.swing.JTextField();
        txtProcesador = new javax.swing.JTextField();
        cboMPMadre = new javax.swing.JComboBox<>();
        txtModeloPMadre = new javax.swing.JTextField();
        cboTDDuro = new javax.swing.JComboBox<>();
        txtMemoriaram = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDatos = new javax.swing.JTable();
        cboBuscar = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Registro de Computadora");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jLabel1)
                .addContainerGap(501, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 70));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sitka Small", 1, 15)); // NOI18N
        jLabel2.setText("Modelo P. Madre");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        txtCapDDuro.setFont(new java.awt.Font("Sitka Small", 1, 15)); // NOI18N
        jPanel2.add(txtCapDDuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 70, 30));

        jLabel3.setFont(new java.awt.Font("Sitka Small", 1, 15)); // NOI18N
        jLabel3.setText("idComputadora");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Small", 1, 15)); // NOI18N
        jLabel4.setText("Procesador");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Small", 1, 15)); // NOI18N
        jLabel5.setText("Memoria Ram");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Small", 1, 15)); // NOI18N
        jLabel6.setText("Tipo Disco Duro");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Small", 1, 15)); // NOI18N
        jLabel7.setText("Cap. D. Duro");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Small", 1, 15)); // NOI18N
        jLabel8.setText("Marc. P. Madre");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        txtidComputadora.setFont(new java.awt.Font("Sitka Small", 1, 15)); // NOI18N
        jPanel2.add(txtidComputadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 60, 30));

        txtProcesador.setFont(new java.awt.Font("Sitka Small", 1, 15)); // NOI18N
        jPanel2.add(txtProcesador, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 180, 30));

        cboMPMadre.setFont(new java.awt.Font("Sitka Small", 1, 15)); // NOI18N
        cboMPMadre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Intel", "AMD" }));
        jPanel2.add(cboMPMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 160, 30));

        txtModeloPMadre.setFont(new java.awt.Font("Sitka Small", 1, 15)); // NOI18N
        jPanel2.add(txtModeloPMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 180, 30));

        cboTDDuro.setFont(new java.awt.Font("Sitka Small", 1, 15)); // NOI18N
        cboTDDuro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Solido", "SATA", "SCII" }));
        jPanel2.add(cboTDDuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 160, 30));

        txtMemoriaram.setFont(new java.awt.Font("Sitka Small", 1, 15)); // NOI18N
        jPanel2.add(txtMemoriaram, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 60, 30));

        btnEliminar.setBackground(new java.awt.Color(204, 255, 102));
        btnEliminar.setFont(new java.awt.Font("Sitka Small", 1, 15)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, 30));

        btnIngresar.setBackground(new java.awt.Color(204, 255, 102));
        btnIngresar.setFont(new java.awt.Font("Sitka Small", 1, 15)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel2.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 30));

        btnActualizar.setBackground(new java.awt.Color(204, 255, 102));
        btnActualizar.setFont(new java.awt.Font("Sitka Small", 1, 15)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, 30));

        tbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDatos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 780, 300));

        cboBuscar.setFont(new java.awt.Font("Sitka Small", 1, 15)); // NOI18N
        cboBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "idComputadora", "Procesador" }));
        jPanel2.add(cboBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 170, -1));

        txtBuscar.setFont(new java.awt.Font("Sitka Small", 1, 15)); // NOI18N
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel2.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 260, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1170, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        ingresar();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        actualizar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tbDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDatosMouseClicked
       int fila = tbDatos.getSelectedRow();
       this.txtidComputadora.setText(this.tbDatos.getValueAt(fila, 0).toString());
       this.txtProcesador.setText(this.tbDatos.getValueAt(fila, 1).toString());
       this.txtMemoriaram.setText(this.tbDatos.getValueAt(fila, 2).toString());
       this.cboTDDuro.setSelectedItem(this.tbDatos.getValueAt(fila, 3).toString());
       this.txtCapDDuro.setText(this.tbDatos.getValueAt(fila, 4).toString());
       this.cboMPMadre.setSelectedItem(this.tbDatos.getValueAt(fila, 5).toString());
       this.txtModeloPMadre.setText(this.tbDatos.getValueAt(fila, 6).toString());
       num = 1;
    }//GEN-LAST:event_tbDatosMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tbDatos.getSelectedRowCount();
        if(fila == 0)
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila");
        else{
            obj.EliminarDatos(tbDatos.getValueAt(tbDatos.getSelectedRow(),0).toString());
            limpiar();
            listar();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        char tecla = evt.getKeyChar();
        if(tecla == KeyEvent.VK_ENTER){
            tbDatos.setModel(obj.getBuscarDatos(cboBuscar.getSelectedIndex(), txtBuscar.getText()));
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmComputadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmComputadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmComputadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmComputadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmComputadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox<String> cboBuscar;
    private javax.swing.JComboBox<String> cboMPMadre;
    private javax.swing.JComboBox<String> cboTDDuro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDatos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCapDDuro;
    private javax.swing.JTextField txtMemoriaram;
    private javax.swing.JTextField txtModeloPMadre;
    private javax.swing.JTextField txtProcesador;
    private javax.swing.JTextField txtidComputadora;
    // End of variables declaration//GEN-END:variables
}
